### PR TITLE
add git docs

### PR DESCRIPTION
**Pull request by malmans2**
- [x] Project, label, and assignee tabs are populated

I thought it would be a good idea to add a section about version control. Just a quick start, no fancy stuff.

### CODE REVIEW

**Review by jdha — APPROVED** [review]
Useful update! I will fork in future - in order to prevent certain individuals (@malmans2) from deleting my branches - haha!
I would note that forking is not always necessary, as one or more devs may well be working on the same branch. In that case we revert to pyNEMO/pyDOMCFG.

**Comment by malmans2** [comment]
pre-commit.ci autofix

**Comment by malmans2** [comment]
> Useful update! I will fork in future - in order to prevent certain individuals (@malmans2) from deleting my branches - haha!

giphy


> I would note that forking is not always necessary, as one or more devs may well be working on the same branch. In that case we revert to pyNEMO/pyDOMCFG.

Good point! I added a note!

**Comment by malmans2** [comment]
I didn't realized the pre-commit bot was also automatically fixing PRs. Not sure if that's always a good thing, so I switched it off (I think @jdha mentioned this the other day).

If the pre-commit check fails, you can ask the bot to apply the fix just commenting: pre-commit.ci autofix
(See https://github.com/pyNEMO/pyDOMCFG/pull/12#issuecomment-853856373)

**Review by jdha — APPROVED** [review]

**Review by jdha — APPROVED** [review]

**Pull request merged**
