### PR TITLE
Add code to generate coordinates datasets

### LINKED ISSUE #6: Datasets for developing
Maybe we should start with adding a module to generate small and simple [xarray Datasets](http://xarray.pydata.org/en/stable/generated/xarray.Dataset.html) with all the input variables we need to get started (e.g., the equivalent of NEMO coordinates/bathymetry files). 

Say we are developing/testing/benchmarking a new function, we can just do something like:
```python
from pydomcfg.datasets import flat_bathy_ds

def create_domain_cfg(ds: Dataset, ...):
    ...
    return domain_cfg_ds

create_domain_cfg(flat_bathy_ds)
```

The real case scenario would become something like:
```python
import pydomcfg
import xarray as xr

ds = xr.open_dataset("bathymetry_orca1.nc")
domain_cfg_ds = pydomcfg.create_domain_cfg(ds)
domain_cfg_ds.to_netcdf("domain_cfg_orca1.nc")
```

This way everything we need to develop is self-contained and we don't have to use/share files with data.

### PR DESCRIPTION
**Pull request by malmans2**
- [x] Closes #6 
- [x] Tests added
- [x] Passes `pre-commit run --all-files`
- [x] Changes are documented in `whats-new.rst`
- [x] New functions/methods are listed in `api.rst`
- [x] Project, label, and assignee tabs are populated

I added a function to generate rectilinear grids. It could be handy in general, so it's public under utils.
E.g.,
```python
from pydomcfg.utils import generate_nemo_rectilinear_grid
ds = generate_nemo_rectilinear_grid(range(1, 10), range(1, 20))
```
I also created a couple of simple bathymetry datasets (flat and island), we can come up with something more interesting when we actually need datasets to test. There's also a placeholder test, just to show how we could make use of this datasets.
Test datasets are not exposed to users in the documentation, but can be accessed with:
```python
from pydomcfg.tests.datasets import ds_flat, ds_island
```

Hopefully I got NEMO's Arakawa right, but double-check!

### CODE REVIEW

**Comment by malmans2** [comment]
@pyNEMO/pydomcfg I'm going to move the function to create the horizontal Cartesian grid under the tests directory. Then other functions could use that one to add different bathy (e.g., channel, ...).

The inputs should be 1D array-like so we are not constrained to regular grids. Currently the function inputs are deltas (just because I thought that's what really matters), and the first point is at (0, 0). Would you guys prefer to switch to x/y coordinates for input? I.e., input lat lon rather than e1 e2?

Also, this is the dataset structure:
```
<xarray.Dataset>
Dimensions:     (x: 5, y: 10)
Coordinates:
    e1t         (y, x) float64 1e+03 1e+03 1e+03 1e+03 ... 1e+03 1e+03 1e+03
    e1v         (y, x) float64 1e+03 1e+03 1e+03 1e+03 ... 1e+03 1e+03 1e+03
    e1f         (y, x) float64 1e+03 1e+03 1e+03 1e+03 ... 1e+03 1e+03 1e+03
    e1u         (y, x) float64 1e+03 1e+03 1e+03 1e+03 ... 1e+03 1e+03 1e+03
    glamt       (y, x) float64 0.0 1e+03 2e+03 3e+03 ... 1e+03 2e+03 3e+03 4e+03
    glamv       (y, x) float64 0.0 1e+03 2e+03 3e+03 ... 1e+03 2e+03 3e+03 4e+03
    nav_lon     (y, x) float64 0.0 1e+03 2e+03 3e+03 ... 1e+03 2e+03 3e+03 4e+03
    glamf       (y, x) float64 500.0 1.5e+03 2.5e+03 ... 2.5e+03 3.5e+03 4.5e+03
    glamu       (y, x) float64 500.0 1.5e+03 2.5e+03 ... 2.5e+03 3.5e+03 4.5e+03
    e2t         (y, x) float64 1e+03 1e+03 1e+03 1e+03 ... 1e+03 1e+03 1e+03
    e2u         (y, x) float64 1e+03 1e+03 1e+03 1e+03 ... 1e+03 1e+03 1e+03
    e2f         (y, x) float64 1e+03 1e+03 1e+03 1e+03 ... 1e+03 1e+03 1e+03
    e2v         (y, x) float64 1e+03 1e+03 1e+03 1e+03 ... 1e+03 1e+03 1e+03
    gphit       (y, x) float64 0.0 0.0 0.0 0.0 0.0 ... 9e+03 9e+03 9e+03 9e+03
    gphiu       (y, x) float64 0.0 0.0 0.0 0.0 0.0 ... 9e+03 9e+03 9e+03 9e+03
    nav_lat     (y, x) float64 0.0 0.0 0.0 0.0 0.0 ... 9e+03 9e+03 9e+03 9e+03
    gphif       (y, x) float64 500.0 500.0 500.0 ... 9.5e+03 9.5e+03 9.5e+03
    gphiv       (y, x) float64 500.0 500.0 500.0 ... 9.5e+03 9.5e+03 9.5e+03
Dimensions without coordinates: x, y
Data variables:
    Bathymetry  (y, x) float64 1e+03 1e+03 1e+03 1e+03 ... 1e+03 1e+03 1e+03
    mask        (y, x) int64 1 1 1 1 1 1 1 1 1 1 1 1 ... 1 1 1 1 1 1 1 1 1 1 1 1
```

Anything missing/redundant? Can we get rid of nav_* and/or mask, or are they gonna be needed?

**Comment by malmans2** [comment]
I slightly changed the original structure.
There's a `generate_cartesian_grid` under utils (eventually will become part of `domhgr` when we are done with `zgr`). The arguments are now face coordinates rather than grid spacing: https://github.com/pyNEMO/pyDOMCFG/blob/3e2b18afaad3a6f5d25a468c03e7c1a8105f4b09/pydomcfg/utils.py#L9

I've also introduced a class to generate test datasets: https://github.com/pyNEMO/pyDOMCFG/blob/3e2b18afaad3a6f5d25a468c03e7c1a8105f4b09/pydomcfg/tests/bathymetry.py#L11

Example usage:
```python
from pydomcfg.tests.bathymetry import Bathymetry
square = Bathymetry(range(10), range(10))
shallow = square.flat(10)
deep = square.flat(1.0e3)
```

If it looks OK let's merge this so @oceandie has a test dataset to get started and @jdha can add methods to `Bathymetry` (e.g., channel, slope, half_bowl, ...)

**Review by oceandie — APPROVED** [review]

**Comment by oceandie** [comment]
> 
> 
> I slightly changed the original structure.
> There's a `generate_cartesian_grid` under utils (eventually will become part of `domhgr` when we are done with `zgr`). The arguments are now face coordinates rather than grid spacing:
> 
> https://github.com/pyNEMO/pyDOMCFG/blob/3e2b18afaad3a6f5d25a468c03e7c1a8105f4b09/pydomcfg/utils.py#L9
> 
I like the idea, just a minor cooment: maybe in the future I would just add some more comments/documentation - it is not immediately clear what you mean by face and center (it depends from where you start) and to track this nomenclature with the Arakawa-C structure. 
> I've also introduced a class to generate test datasets:
> 
> https://github.com/pyNEMO/pyDOMCFG/blob/3e2b18afaad3a6f5d25a468c03e7c1a8105f4b09/pydomcfg/tests/bathymetry.py#L11
> 
> Example usage:
> 
> ```python
> from pydomcfg.tests.bathymetry import Bathymetry
> square = Bathymetry(range(10), range(10))
> shallow = square.flat(10)
> deep = square.flat(1.0e3)
> ```
> 
> If it looks OK let's merge this so @oceandie has a test dataset to get started and @jdha can add methods to `Bathymetry` (e.g., channel, slope, half_bowl, ...)

**Comment by jdha** [comment]
minor semantics, but would it not be cleaner for
`generate_cartesian_grid(x_f, y_f)`
to take the _nemo-like_ form
`generate_cartesian_grid(ppe1_m, ppe2_m, jpiglo, jpjglo)`
this would also allow the bathy tests to be constructed using single parameters rather than vectors (and possibly even using a namelist?)

**Comment by malmans2** [comment]
Makes sense! How about if `ppe{1,2}_m` is a vector `jp{i,j}glo` must be `None`, otherwise `jp{i,j}glo` must be an integer? So we cover all cartesian grids and we align with NEMO namelists? 
So we would revert to users providing grid spacing rather than coordinates (@oceandie thoughts?). We could probably support both grid spacing/coordinates as input, but I think this would just over-complicate things. 
I guess we could also add `ppg{lam,phi}0`, by default set to (0, 0).

**Comment by oceandie** [comment]
> 
> 
> Makes sense! How about if `ppe{1,2}_m` is a vector `jp{i,j}glo` must be `None`, otherwise `jp{i,j}glo` must be an integer? So we cover all cartesian grids and we align with NEMO namelists?
> So we would revert to users providing grid spacing rather than coordinates (@oceandie thoughts?). We could probably support both grid spacing/coordinates as input, but I think this would just over-complicate things.
> I guess we could also add `ppg{lam,phi}0`, by default set to (0, 0).
I agree with both your suggestions - than in the end this will be just for testing our zgr developments ....

**Comment by jdha** [comment]
> I agree with both your suggestions - than in the end this will be just for testing our zgr developments ....

It won't be just for testing zgr dev as the unit tests will probably continue to use this (+ it'll be integrated into hgr later). Happy to go with @malmans2 _hybrid_ suggestion.

**Comment by oceandie** [comment]
> 
> 
> > I agree with both your suggestions - than in the end this will be just for testing our zgr developments ....
> 
> It won't be just for testing zgr dev as the unit tests will probably continue to use this (+ it'll be integrated into hgr later). Happy to go with @malmans2 _hybrid_ suggestion.

I have some doubts regarding the later integration into hgr - I think if we'll go towards a general curvilinear grid approach (where the cartesian grid is just a special case), the structure will be a bit different - but happy to go now and think about this later on

**Comment by malmans2** [comment]
OK, I think it's in good shape now. Please have another look and feel free to merge if it's good to go!

**Pull request merged**
