### PR TITLE
Test calc rmax closes #48

### LINKED ISSUE #48: testing calc_rmax
I found some inconsistencies in the way calc_rmax works. I've developed a quick python code for:
1) read AMM7 bathymetry;
2) create an envelope bathymetry and smooth it: it implements exactly NEMO Fortran90 code (very inefficient but at least we know what it does)
3) compute the maximum rmax with three different codes: original numpy version of James; xarray version of James code; my old code (actually adapted from pyROMS, it very inefficient but I think it is clear what it does).

If we smooth the envelope with an rn_rmax threshold of 0.24, the following is the pring of the iterative smoothing:
`python test_rmax_calc.py`  
`Iter: 1 rmax:  1.0`
`Iter: 2 rmax:  0.9353992591835926`
`Iter: 3 rmax:  0.9187177073344386`
`Iter: 4 rmax:  0.8765126597150313`
`Iter: 5 rmax:  0.8185786808404448`
`Iter: 6 rmax:  0.7347370279088926`
`Iter: 7 rmax:  0.7347370279088925`
`Iter: 8 rmax:  0.6074021541852422`
`Iter: 9 rmax:  0.5717732932642535`
`Iter: 10 rmax:  0.4755012414806615`
`Iter: 11 rmax:  0.37086087298353765`
`Iter: 12 rmax:  0.24000000000000007`

The  rmax computed by the three codes are the following:
1. calc_rmax_xr: 0.34985075453036585 (xarray code)
2. calc_rmax_np: 0.34985075453036585 (numpy code)
3. SlopeParam: 0.24000000000000005 (ROMS code)

### PR DESCRIPTION
**Pull request by oceandie**
- [ ] Closes #xxxx
- [ ] Tests added
- [ ] Passes `pre-commit run --all-files`
- [ ] Changes are documented in `whats-new.rst`
- [ ] New functions/methods are listed in `api.rst`
- [ ] Project, label, and assignee tabs are populated

### CODE REVIEW

**Comment by oceandie** [comment]
https://www.dropbox.com/s/u3nl4htrynfi89x/bathymeter_mo_ps43.nc?dl=0
this is the link for AMM7 bathymetry ... let me know if you cannot use it

**Comment by oceandie** [comment]
I added the last implementation of xarray-calc_max (using the maximum rather than the average). I hope I am not doing anything stupidly wrong, if yes, sorry in advance :)

**Comment by jdha** [comment]
Not that I should be looking at this, but ...

To reproduce your SlopeParam code @oceandie [which looks very much like my old Matlab ;) ] I did the following (see below). The large values seem to appear in the outer halo as they where included in the np.diff (your code only goes from the second index to the last but one) ... I also think I'd got the indices out of sync by 1 - but I'm not too sure ... I'll look again on Monday (and do an XR version of this).

If I diff the the results from the following code with SlopeParam they match.

```
def calc_rmax_np(depth):
    """
    Calculate rmax: measure of steepness

    This function returns the slope steepness criteria rmax, which is simply
    (H[0] - H[1]) / (H[0] + H[1])
    Parameters
    ----------
    depth: float
            Bottom depth (units: m).
    Returns
    -------
    rmax: float
            Slope steepness value (units: None)
    """
    
    rmax_x, rmax_y = np.zeros_like(depth), np.zeros_like(depth)

    rmax_x[1:-1, 1:-1] = np.maximum (
        np.abs( np.diff(depth[1:-1, :-1], axis=1) / (depth[1:-1,  :-2] + depth[1:-1, 1:-1]) ),
        np.abs( np.diff(depth[1:-1,1:  ], axis=1) / (depth[1:-1, 1:-1] + depth[1:-1, 2:  ]) )
    )
    rmax_y[1:-1, 1:-1] = np.maximum (
        np.abs( np.diff(depth[ :-1, 1:-1], axis=0) / (depth[ :-2, 1:-1] + depth[1:-1, 1:-1]) ) ,
        np.abs( np.diff(depth[1:  , 1:-1], axis=0) / (depth[1:-1, 1:-1] + depth[2:,   1:-1]) )
    )

    return np.maximum(np.abs(rmax_x), np.abs(rmax_y))
```

**Comment by jdha** [comment]
for xr updated see #49

**Pull request closed without merging**
